version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /docs
    schedule:
      interval: weekly
    allow:
      - dependency-type: all

  - package-ecosystem: bundler
    directory: /Library/Homebrew
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: sorbet-runtime
